### ISSUE TITLE
I can't get other add-ons out of the bar.

### ISSUE THREAD

**Issue by sam-baker** [Geek-in-Training/Firefox-Addon-Bar--Restored#10]
I am using the typegauge plugin, which installs an icon in the status bar, which is gone now.  Installed your addon and was able to finally see the typegauge icon.  I tried moving the icon to the current add-on bar, but it still seems like it's inside of your new bar.  If I disable your bar, the icon goes away.

Is there a way to move an icon out of your bar into the built-in bar?  Or am I missing something obvious?

**Comment by Geek-in-Training** [comment]
Well, not terribly obvious.
A little background:  Any Firefox version less than 4.0 had what was called the status-bar. It displayed, well, status things, such as a progress bar, and it used to show you where a link you were hovering over would go to if you clicked on it. So back then, when you made an addon, you could add stuff into the status-bar for easy access. So you would write fancy computer code that basically says: [add "myStatusThing" to "status-bar"].

_**Enter Firefox 4.0**_

Now there was no more status bar, and they added the addon bar in its place. But, so that old addons would still be compatible, they added a sub-bar, or a section of the addon bar, and named it "status-bar" so that these old addons would still work.  This "sub-bar" and its contents could not be moved anywhere, they just sat on the addon bar's far right.

_**Enter Firefox 29**_

No more addon bar, or it's status-bar "sub-bar". Any addon that tries to put anything in the addon bar now moves into the navigation bar, unless it is too big.  The status-bar still exists, but it is hidden, and so anything inside of it is also hidden.

_**Enter The Addon Bar (Restored)**_

So now with this addon I can move the old status-bar into my new addon bar, and I can make the whole bar movable. But not each item inside of it.

Hope that makes sense, it is a little hard to explain clearly without explaining how the code itself works.

**Comment by Geek-in-Training** [comment]
In Short:
Yes, it is in a way "inside" _The Addon Bar (Restored)_,  because the status bar is hidden by default, you can't see it even if you move it off the addon bar if you have it disabled.
